import test from 'node:test';
import assert from 'node:assert/strict';
import {calculateBudget,calculateActualResult,calculateVariance,calculateWeeklyScore,calculateFinalScore} from '../src/engine.js';
import {EVENTS} from '../src/data.js';
test('base budget and cash restrictions',()=>{const b=calculateBudget({target:500,stock:500,marketing:0});assert.equal(b.profit,3250000);assert.equal(b.endingCash,18250000);assert.equal(b.valid,true);assert.equal(calculateBudget(b,100).valid,false);assert.equal(calculateBudget({...b,target:250.5}).valid,false)});
test('every event respects demand, inventory, expense and cash accounting',()=>{for(const event of EVENTS)for(const accepted of [false,true])for(const fluctuation of [.9,1,1.1]){const b=calculateBudget({target:600,stock:550,marketing:500000});const a=calculateActualResult(b,event,accepted,15000000,fluctuation);assert.ok(a.sold<=a.demand&&a.sold<=b.stock);assert.equal(a.expenses,a.material+a.marketing+a.fixed);assert.equal(a.profit,a.revenue-a.expenses);assert.equal(a.endingCash,15000000+a.profit);assert.equal(a.waste,550-a.sold)}});
test('supplier increase charges all prepared stock',()=>{const b=calculateBudget({target:500,stock:800,marketing:0});const a=calculateActualResult(b,EVENTS[2],false,15000000,1);assert.equal(a.material,5520000);assert.equal(a.waste,300);assert.equal(calculateVariance(b,a).find(r=>r.key==='material').favorable,false)});
test('decision decline has no cost or effect; acceptance applies both',()=>{const b=calculateBudget({target:800,stock:800,marketing:0});const no=calculateActualResult(b,EVENTS[6],false,15000000,1);const yes=calculateActualResult(b,EVENTS[6],true,15000000,1);assert.equal(no.demand,500);assert.equal(no.marketing,0);assert.equal(yes.demand,700);assert.equal(yes.marketing,750000)});
test('four weeks reconcile and scores remain bounded',()=>{let cash=15000000;const history=[];for(let i=0;i<4;i++){const budget=calculateBudget({target:500,stock:500,marketing:0},cash);const actual=calculateActualResult(budget,EVENTS[3],false,cash,1);history.push({budget,actual});cash=actual.endingCash;assert.equal(calculateWeeklyScore(budget,actual).accuracy,100)}const s=calculateFinalScore(history);assert.equal(s.endingCash,cash);assert.equal(s.profit,13000000);assert.equal(s.efficiency,100);assert.equal(s.score,100)});
