import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Leaf,ArrowRight,ArrowUpRight,HelpCircle,RotateCcw,X,Wallet,TrendingUp,Coffee,Check,CloudRain,Sparkles,Heart,Package,Zap,Wrench,Target,Megaphone,ChevronRight,Trophy,BookOpen,Store} from 'lucide-react';
import {BUSINESS as B,MARKETING,EVENTS,LESSONS} from './data';
import {rupiah as rp,calculateBudget,calculateActualResult,calculateVariance,calculateWeeklyScore,calculateFinalScore} from './engine';
import './style.css';
const KEY='tealab-game-v1';
const initial=()=>({stage:'landing',cash:B.capital,history:[],plan:{target:500,stock:500,marketing:250000}});
function restore(){try{const s=JSON.parse(localStorage.getItem(KEY));return s&&['landing','planning','event','result','final'].includes(s.stage)&&Array.isArray(s.history)&&s.history.length<=4&&Number.isFinite(s.cash)&&s.plan&&(!['event','result'].includes(s.stage)||s.event&&s.budget)?s:initial()}catch{return initial()}}
const icons={spark:Sparkles,rain:CloudRain,box:Package,heart:Heart,bolt:Zap,tool:Wrench};
function App(){
 const [game,setGame]=useState(restore),[modal,setModal]=useState(null),[saveError,setSaveError]=useState(false);
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(game));setSaveError(false)}catch{setSaveError(true)}},[game]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'smooth'})},[game.stage]);
 const week=Math.min(4,game.history.length+(game.stage==='result'?0:1));
 const budget=calculateBudget(game.plan,game.cash),last=game.history.at(-1);
 function confirm(){if(!budget.valid)return;setGame({...game,stage:'event',budget,event:EVENTS[Math.floor(Math.random()*EVENTS.length)],fluctuation:.9+Math.random()*.2})}
 function resolve(accepted){if(accepted&&game.event.decision&&game.budget.expenses+game.event.cost>game.cash)return;const actual=calculateActualResult(game.budget,game.event,accepted,game.cash,game.fluctuation);setGame({...game,stage:'result',cash:actual.endingCash,history:[...game.history,{budget:game.budget,actual,event:game.event,accepted}]})}
 return <><header><a className="brand" href="#" onClick={e=>{e.preventDefault();setModal('help')}}><span className="logo"><Leaf size={23}/></span>TEA TYCOON<span className="brand-sub">by tealab.</span></a><div className="header-right">{game.stage!=='landing'&&<span className="header-week">Minggu {week} <span>/ 4</span></span>}<button className="icon-button" aria-label="Cara bermain" onClick={()=>setModal('help')}><HelpCircle size={21}/></button>{game.stage!=='landing'&&<button className="icon-button" aria-label="Mulai ulang" onClick={()=>setModal('restart')}><RotateCcw size={19}/></button>}</div></header>
 {saveError&&<p role="status" className="notice">Penyimpanan tidak tersedia. Progres tetap bisa dimainkan selama halaman ini terbuka.</p>}
 <main>{game.stage==='landing'?<Landing onStart={()=>setGame({...game,stage:'planning'})} onHelp={()=>setModal('help')}/>:<>
 <div className="game-top"><div><div className="eyebrow">KEDAI KECIL, RENCANA BESAR</div><h1>{game.stage==='final'?'Cerita sukses dimulai dari rencana.':game.stage==='planning'?'Saatnya meracik rencana.':game.stage==='event'?'Ada kabar dari kedai!':`Hasil minggu ${week}`}</h1><p>{game.stage==='planning'?'Seimbangkan ambisi, persediaan, dan modalmu.':game.stage==='event'?'Dunia bisnis penuh kejutan. Siapkan keputusan terbaikmu.':game.stage==='final'?'Empat minggu perjalanan Tealab, dalam satu laporan.':'Setiap hasil adalah bekal untuk keputusan berikutnya.'}</p></div><CashBalanceCard cash={game.cash}/></div>
 <WeekProgress game={game} week={week}/>
 {game.stage==='planning'&&<><div className="planning-grid"><section className="card"><div className="section-title"><span className="icon-tile"><Coffee/></span><div><h2>Racikan anggaran</h2><p>Rencana operasional minggu {week}</p></div><span className="tag">01 / RENCANA</span></div><BudgetInputCard title="Target penjualan" icon={Target} value={game.plan.target} onChange={v=>setGame({...game,plan:{...game.plan,target:v}})} hint="Berapa gelas yang ingin kamu jual?"/><BudgetInputCard title="Stok / kapasitas produksi" icon={Package} value={game.plan.stock} onChange={v=>setGame({...game,plan:{...game.plan,stock:v}})} hint="Seluruh stok dikenakan biaya bahan, termasuk yang tidak terjual."/><div className="input-block"><label><Megaphone size={18}/> Anggaran pemasaran</label><p>Jangkau lebih banyak pencinta teh.</p><div className="marketing-options">{MARKETING.map((v,i)=><button key={v} className={game.plan.marketing===v?'selected':''} onClick={()=>setGame({...game,plan:{...game.plan,marketing:v}})}>{v===0?'Tanpa iklan':`${v/1000} rb`}<small>+{i*5}% permintaan</small></button>)}</div></div><div className="tip"><Leaf size={20}/><span>Pasar normal sekitar <b>500 gelas/minggu</b>, dengan fluktuasi ±10%. Pemasaran dan kejadian bisnis ikut memengaruhi permintaan.</span></div></section><BudgetSummary budget={budget} confirm={confirm}/></div><div className="assumptions"><span><Coffee size={17}/> Harga jual <b>{rp(B.price)}/gelas</b></span><span><Package size={17}/> Bahan baku <b>{rp(B.material)}/gelas</b></span><span><Store size={17}/> Biaya tetap <b>{rp(B.fixed)}/minggu</b></span></div>{last&&<div className="notice">Bekal minggu lalu: laba {rp(last.actual.profit)} · selisih laba {rp(last.actual.profit-last.budget.profit)} · stok tersisa {last.actual.waste} gelas.</div>}</>}
 {game.stage==='event'&&<EventCard game={game} resolve={resolve}/>}
 {game.stage==='result'&&<Results entry={last} onNext={()=>setGame({...game,stage:game.history.length===4?'final':'planning'})} final={game.history.length===4}/>}
 {game.stage==='final'&&<FinalReport history={game.history} restart={()=>setModal('restart')}/>}
 </>}</main><footer><span><Leaf size={15}/> TEALAB · Diracik dengan rencana.</span><span>AFL 1 — MK Budgeting <span className="footer-dot">•</span> Anggaran dan Fungsi Anggaran</span></footer>
 {modal&&<Modal close={()=>setModal(null)} title={modal==='help'?'Cara bermain':'Mulai perjalanan baru?'}>{modal==='help'?<><p>Kelola Tealab selama <b>4 minggu virtual</b> dengan modal awal <b>{rp(B.capital)}</b>.</p><div className="steps">{['Susun anggaran','Hadapi kejadian bisnis','Ambil keputusan','Lihat hasil aktual','Bandingkan anggaran vs realisasi','Evaluasi dan lanjut ke minggu berikutnya'].map((s,i)=><div key={s}><span>{i+1}</span>{s}</div>)}</div><p>Stok yang tidak terjual dianggap terbuang di akhir minggu. Sisakan kas untuk kejutan dan sesuaikan rencana dari hasil sebelumnya.</p><button className="primary full" onClick={()=>{setModal(null);if(game.stage==='landing')setGame({...game,stage:'planning'})}}>Siap, ayo mulai <ArrowRight size={18}/></button></>:<><p>Semua anggaran dan riwayat permainan ini akan dihapus. Kamu akan mulai kembali dengan modal Rp15.000.000.</p><div className="actions"><button className="secondary" onClick={()=>setModal(null)}>Batal</button><button className="primary" onClick={()=>{setGame(initial());setModal(null)}}>Ya, mulai ulang</button></div></>}</Modal>}</>
}
function Landing({onStart,onHelp}){return <><div className="landing-grid"><section className="hero"><div className="eyebrow"><span className="live-dot"/> SIMULASI BISNIS TEH INTERAKTIF</div><h1>Kedai tehmu.<br/>Keputusanmu.<br/><em>Cerita suksesmu.</em></h1><div className="hero-subtitle">TEA TYCOON <span>Budget • Brew • Grow</span></div><p>Kelola bisnis tehmu, susun anggaran, hadapi perubahan pasar, dan buktikan bahwa keputusan yang tepat dapat membuat bisnis bertahan dan berkembang.</p><div className="actions"><button className="primary" onClick={onStart}>Mulai bermain <ArrowRight size={19}/></button><button className="secondary" onClick={onHelp}><BookOpen size={18}/> Cara bermain</button></div><div className="hero-facts"><span><b>4</b> minggu virtual</span><span><b>Rp15 jt</b> modal awal</span><span><b>∞</b> pelajaran bisnis</span></div></section><TeaShop/></div><section className="landing-bottom"><div><span className="eyebrow">BELAJAR SAMBIL MERACIK</span><h2>Ide besar. Mulai dari satu gelas.</h2></div>{[[Target,'Rencanakan','Susun anggaran yang masuk akal.'],[Coffee,'Jalankan','Hadapi kejutan di balik bar.'],[TrendingUp,'Kembangkan','Evaluasi hasil, perbaiki strategi.']].map(([Icon,title,description])=><div className="feature" key={title}><span className="icon-tile"><Icon size={22}/></span><h3>{title}</h3><p>{description}</p></div>)}</section></>}
function TeaShop(){return <div className="shop-scene" aria-label="Ilustrasi kedai teh Tealab dengan meja bar, tanaman, dan minuman teh"><div className="scene-orbit"/><span className="scene-spark s1">✳</span><span className="scene-spark s2">✳</span><div className="scene-label"><span className="live-dot"/> BISNIS IMPIANMU, DIMULAI DI SINI</div><div className="shop"><div className="shop-sign">tealab<span>TEH SEGAR, IDE SEGAR</span></div><div className="awning"><i/><i/><i/><i/><i/><i/><i/></div><div className="shop-interior"><div className="shelf"><span>✿</span><span>▥</span><span>▥</span></div><div className="shop-menu">MENU HARI INI<hr/>MATCHA LATTE<br/>JASMINE TEA<br/>MILK TEA<small>diracik sepenuh hati ♡</small></div><div className="barista"><div className="hair"/><div className="face">‿</div><div className="apron"><Leaf size={24}/></div></div><div className="tea-cup cup-one"><Leaf size={21}/></div><div className="tea-cup cup-two"><Leaf size={21}/></div></div><div className="counter"><span>setiap gelas punya cerita.</span></div><div className="shop-base"/></div><div className="plant"><span>❧</span><div/></div><div className="floating-note"><span className="icon-tile"><TrendingUp size={22}/></span><div><small>Racikan sukses</small><b>Strategi + secangkir teh</b></div></div><div className="open-sign">BUKA<br/><small>TEH NIKMAT • HARI HANGAT</small></div><div className="scene-caption">SEJAK 2026 <span>✦</span> AWAL CERITA BESARMU</div></div>}
function CashBalanceCard({cash}){return <div className="cash-card"><Wallet size={23}/><div><small>Saldo kas saat ini</small><b>{rp(cash)}</b></div></div>}
function WeekProgress({game,week}){return <div className="week-progress">{[1,2,3,4].map(n=>{const h=game.history[n-1];return <div key={n} className={`week-item ${n===week?'current':''} ${h?'complete':''}`}><span className="week-number">{h?<Check size={17}/>:n}</span><div><b>Minggu {n}</b>{h?<small>Pendapatan {rp(h.actual.revenue)}<br/>Laba {rp(h.actual.profit)} · Δ {rp(h.actual.profit-h.budget.profit)}</small>:<small>{n===week?'Sedang berlangsung':'Menunggu racikanmu'}</small>}</div></div>})}</div>}
function BudgetInputCard({title,icon:Icon,value,onChange,hint}){return <div className="input-block"><div className="input-heading"><label htmlFor={title}><Icon size={18}/> {title}</label><div className="number-field"><input id={title} type="number" min="250" max="800" step="1" value={value} onChange={e=>onChange(e.target.value===''?'':Number(e.target.value))}/><span>gelas</span></div></div><p>{hint}</p><input aria-label={`${title} slider`} className="slider" type="range" min="250" max="800" step="10" value={value||250} onChange={e=>onChange(Number(e.target.value))}/><div className="range-labels"><span>250 gelas</span><span>800 gelas</span></div></div>}
function BudgetSummary({budget:b,confirm}){return <aside className="budget-summary"><div className="eyebrow">RENCANA YANG BAIK, AWAL YANG BAIK</div><h2>Ringkasan anggaran</h2><div className="summary-line"><span>Penjualan</span><b>{rp(b.revenue)}</b></div><div className="summary-line"><span>Bahan baku</span><b>{rp(b.material)}</b></div><div className="summary-line"><span>Biaya tetap</span><b>{rp(b.fixed)}</b></div><div className="summary-line"><span>Pemasaran</span><b>{rp(b.marketing)}</b></div><div className="summary-total"><span>Estimasi laba</span><strong>{rp(b.profit)}</strong><small>Proyeksi kas akhir <b>{rp(b.endingCash)}</b></small></div>{b.target>b.stock&&<p className="budget-warning">Target melebihi stok: kapasitas saat ini tidak cukup untuk mencapai target penjualan.</p>}{!b.valid&&<p className="budget-warning" role="alert">Gunakan 250–800 gelas (bilangan bulat) dan pastikan total biaya tidak melebihi kas.</p>}<button className="light-button full" disabled={!b.valid} onClick={confirm}>Konfirmasi anggaran <ArrowRight size={18}/></button><p className="summary-foot">Anggaran dikunci setelah dikonfirmasi.</p></aside>}
function EventCard({game,resolve}){const e=game.event,Icon=icons[e.icon],affordable=game.cash>=game.budget.expenses+(e.cost||0);return <section className="event-card card"><span className="eyebrow">KEJADIAN BISNIS MINGGU INI</span><div className="event-icon"><Icon size={47}/></div><h2>{e.title}</h2><p>{e.description}</p><div className="effect"><Sparkles size={18}/>{e.effect}</div>{e.decision?<><h3>Apakah kamu ingin mengambil kesempatan ini?</h3><p>Stok tetap {game.budget.stock} gelas. Permintaan tambahan belum tentu menjadi penjualan.</p><div className="actions"><button className="primary" disabled={!affordable} onClick={()=>resolve(true)}>Ya, {e.id==='festival'?'ikut festival':'ambil tawaran'} <ArrowRight size={18}/></button><button className="secondary" onClick={()=>resolve(false)}>Tidak, lanjutkan rencana</button></div>{!affordable&&<p role="status">Kas setelah alokasi anggaran tidak cukup untuk biaya kesempatan ini.</p>}</>:<button className="primary" onClick={()=>resolve(false)}>Jalankan kedai & lihat hasil <ArrowRight size={18}/></button>}</section>}
function ActualResultCard({label,value,positive}){return <div className={`stat-card ${positive?'highlight':''}`}><small>{label}</small><strong>{value}</strong></div>}
const names={revenue:'Penjualan',material:'Bahan baku',marketing:'Pemasaran',fixed:'Biaya tetap / tambahan',profit:'Laba'};
function VarianceTable({budget,actual}){return <section className="card"><h2>Anggaran vs realisasi</h2><p>Selisih = realisasi − anggaran. Biaya yang lebih rendah menguntungkan.</p><div className="table-scroll"><table><thead><tr><th>Kategori</th><th>Anggaran</th><th>Realisasi</th><th>Selisih</th></tr></thead><tbody>{calculateVariance(budget,actual).map(r=><tr key={r.key}><th>{names[r.key]}</th><td>{rp(r.budget)}</td><td>{rp(r.actual)}</td><td className={r.delta===0?'neutral':r.favorable?'favorable':'unfavorable'}>{r.delta>0?'+':''}{rp(r.delta)}<small>{r.delta===0?'Sesuai rencana':r.favorable?'Menguntungkan':'Tidak menguntungkan'}</small></td></tr>)}</tbody></table></div></section>}
function VarianceAnalysis({entry:{budget:b,actual:a,event:e,accepted}}){return <section className="analysis card"><div className="section-title"><span className="icon-tile"><BookOpen size={21}/></span><h2>Di balik angka</h2></div><p>Laba aktual {a.profit===b.profit?'sesuai':a.profit>b.profit?'melampaui':'di bawah'} anggaran sebesar <b>{rp(Math.abs(a.profit-b.profit))}</b>. {a.profit===b.profit?'Tidak ada selisih laba.':a.profit>b.profit?'Selisih ini menguntungkan.':'Selisih ini tidak menguntungkan.'}</p><p>Pasar berfluktuasi {((a.fluctuation-1)*100).toFixed(1)}%. Setelah pemasaran dan kejadian “{e.title}”{e.decision?accepted?' yang diambil':' yang dilewatkan':''}, permintaan mencapai <b>{a.demand} gelas</b>; terjual <b>{a.sold} gelas</b>.</p>{a.missed>0&&<p>Stok membatasi penjualan: {a.missed} gelas permintaan belum terpenuhi. Pertimbangkan kapasitas tambahan jika permintaan ini berkelanjutan.</p>}{a.waste>0&&<p>{a.waste} gelas tidak terjual tetapi tetap dikenakan biaya bahan. Sesuaikan stok untuk mengurangi pemborosan.</p>}{e.material&&<p>Kenaikan harga supplier membuat biaya bahan meningkat 15% dari anggaran.</p>}{e.expense>0&&<p>Biaya tak terduga {rp(e.expense)} menambah pengeluaran minggu ini.</p>}{accepted&&e.decision&&<p>Keputusan promosi menambah biaya pemasaran {rp(e.cost)}. Evaluasi apakah tambahan penjualan menutup biaya tersebut.</p>}<div className="tip"><Target size={20}/><span>Akurasi anggaran {calculateWeeklyScore(b,a).accuracy.toFixed(1)}% · Efisiensi stok {calculateWeeklyScore(b,a).efficiency.toFixed(1)}%</span></div></section>}
function Results({entry,onNext,final}){const a=entry.actual;return <><div className="stats-grid"><ActualResultCard label="Gelas terjual" value={`${a.sold} gelas`}/><ActualResultCard label="Pendapatan aktual" value={rp(a.revenue)}/><ActualResultCard label="Pengeluaran aktual" value={rp(a.expenses)}/><ActualResultCard label="Laba aktual" value={rp(a.profit)} positive/><ActualResultCard label="Kas akhir" value={rp(a.endingCash)}/></div><VarianceTable budget={entry.budget} actual={a}/><VarianceAnalysis entry={entry}/><div className="next-row"><span>Catat pelajarannya. Racik strategi berikutnya.</span><button className="primary" onClick={onNext}>{final?'Lihat laporan akhir':'Rencanakan minggu berikutnya'} <ArrowRight size={18}/></button></div></>}
function FinalReport({history,restart}){const s=calculateFinalScore(history);return <><div className="report-grid"><section className="score-card"><Trophy size={43}/><div className="eyebrow">TEALAB · SKOR BISNIS</div><div className="score">{s.score}<span>/ 100</span></div><h2>{s.label}</h2><p>Bisnis bertumbuh dari keputusan yang terus diperbaiki.</p></section><section className="card"><div className="eyebrow">TEALAB</div><h2>Laporan akhir bisnis</h2><div className="report-stats">{[['Total pendapatan',rp(s.revenue)],['Total pengeluaran',rp(s.expenses)],['Laba bersih',rp(s.profit)],['Kas akhir',rp(s.endingCash)],['Rata-rata akurasi anggaran',`${s.accuracy.toFixed(1)}%`],['Efisiensi persediaan',`${s.efficiency.toFixed(1)}%`]].map(([label,value])=><ActualResultCard key={label} label={label} value={value}/>)}</div></section></div><section className="card score-details"><h2>Bagaimana skormu dihitung?</h2>{[['Profitabilitas',40,s.profitability],['Akurasi anggaran',30,s.accuracy],['Pengelolaan kas',20,s.cash],['Efisiensi operasional',10,s.efficiency]].map(([label,weight,value])=><div className="score-line" key={label}><span>{label} <small>Bobot {weight}%</small></span><progress max="100" value={value}/><b>{value.toFixed(0)}/100</b></div>)}<p>Profitabilitas: laba bersih ÷ target empat minggu Rp10.000.000, dibatasi 0–100%. Akurasi per minggu: 1 − |laba aktual − laba anggaran| ÷ nilai terbesar antara |laba anggaran| dan Rp1.250.000, dibatasi 0–100%. Pengelolaan kas: proporsi minggu dengan kas akhir positif. Efisiensi: total gelas terjual ÷ total stok.</p></section><section className="learning"><div className="eyebrow">LEBIH DARI SEKADAR JUALAN TEH</div><h2>Apa yang dipelajari?</h2><div className="lesson-grid">{LESSONS.map(([title,description],i)=><div key={title}><span>0{i+1}</span><h3>{title}</h3><p>{description}</p></div>)}</div></section><div className="next-row"><span>Rencana baru, peluang baru.</span><button className="primary" onClick={restart}><RotateCcw size={18}/> Main lagi</button></div></>}
function Modal({title,children,close}){const ref=React.useRef(null);useEffect(()=>{const prior=document.activeElement;ref.current?.focus();function onKey(e){if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=ref.current.querySelectorAll('button');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}document.addEventListener('keydown',onKey);const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',onKey);document.body.style.overflow=prev;prior?.focus()}},[]);return <div className="modal-backdrop" onClick={close}><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="modal-title" className="modal card" onClick={e=>e.stopPropagation()}><button className="close-button icon-button" aria-label="Tutup" onClick={close}><X/></button><h2 id="modal-title">{title}</h2>{children}</section></div>}
createRoot(document.getElementById('root')).render(<App/>);

